project:
  type: website
  output-dir: docs

website:
  title: "Haibin Bai"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Example analysis"
        href: ExAanalysis.qmd

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true

editor: visual

